pipeline{
    
    agent any
    stages{
        
        stage('Compile stage'){
            steps{
           def mvnHome = tool name: 'MAVEN_HOME', type: 'maven'
            sh "${mvnHome}/bin/mvn package"
            }

            }

        }

    

}
